name: push_socket_client_dart
description: "This package helps to connect to Push backend using websockets built on top of Socket.IO"
version: 0.0.1-alpha
homepage: https://docs.push.org/developers/developer-tooling/push-sdk/sdk-packages-details/pushprotocol-socket
repository: https://github.com/ethereum-push-notification-service/push-socket-client-dart

environment:
  sdk: ^3.0.4

# Add regular dependencies here.
dependencies:
  ethereum_addresses: ^1.0.2
  socket_io_client: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
